### ISSUE TITLE
Question about the huge number of unknown factions/OTUs ?

### ISSUE THREAD

**Issue by michoug** [bwemheu/Tax4Fun2#1]
Hi,
When running the KELP example with the last version

```
runRefBlast(path_to_otus = "KELP_otus.fasta", path_to_reference_data = PATH, path_to_temp_folder = "Kelp_Ref99NR", database_mode = "Ref99NR", use_force = T, num_threads = 2)
makeFunctionalPrediction(path_to_otu_table = "KELP_otu_table.txt", path_to_reference_data = PATH, path_to_temp_folder = "Kelp_Ref99NR", database_mode = "Ref99NR", normalize_by_copy_number = T, min_identity_to_reference = 0.97, normalize_pathways = F)
```
I looked at the logfile and saw these values

```
Tax4fun2 beta
Tue Jul  2 12:17:03 2019
Unknown fraction (amount of otus unused in the prediction) for each sample:
X57884: 0.98451
X57885: 0.98753
X57886: 0.99034
X57887: 0.96078
X57888: 0.98645
X57889: 1
```
Which tends to mean that nearly all OTUs were discarded for the functional prediction?
When the average % of otus discarded is 98%, I wonder if I can really trust these data?

**Comment by bwemheu** [comment]
Hi,

sorry for the late reply. You cannot really trust a prediction with high FTU and FSU values. The Kelp data contains many otus with no close reference genome. Including your own data usually helps to solve this problem. FTUs and FSUs in Tax4Fun2 are, in my opinion, much more realistic than in Tax4Fun which had no identity cutoff. PICRUSt would provide high NSTI values for the KELP data (-> high distance to the closest relative in the reference database) but would still use all OTUs with significant hits in greengenes in the prediction which results in low quality, functional profile.
