### ISSUE TITLE
Problem with runRefBlast

### ISSUE THREAD

**Issue by MYC-TW** [bwemheu/Tax4Fun2#10]
Hello Bernd,

I am a Windows10 user. I installed everything successfully. I have tested reference data, built the dependencies, and added the bin to PATH. 

When I try to run the reference blast with the test data using the command:
runRefBlast(path_to_otus = "D:/Tax4Fun2/KELP_otus.fasta", path_to_reference_data = "D:/Tax4Fun2/Tax4Fun2_ReferenceData_v2", database_mode = "Ref99NR", use_force = TRUE, num_threads = 2)

I got the following response and error message: 
Copy and generate database
Reference blast started
Error in if (file.size(path_to_blast_file) == 0) stop("Blast file empty!") : 
  missing value where TRUE/FALSE needed

Any help would be very much appreciated.

Thanks,

Ming-Yi

**Comment by bwemheu** [comment]
Hi,

A small bug in the runRefBlast script. It called makeblastdb instead of blastn. Download the final release of 1.1.5 to get rid of the error.

Thanks!
