### ISSUE TITLE
Problems with BLAST

### ISSUE THREAD

**Issue by ThiagoRBM** [bwemheu/Tax4Fun2#3]
Hello, 

I'm a Windows user and following the README, it is said that sometimes we have to manually download the reference database.
I did this but, when I try to build the dependencies, I get this error: Error in buildDependencies(path_to_working_directory = ".", install_suggested_packages = TRUE) : 
  unused argument (path_to_working_directory = ".")

Also, I cant get help from ?buildDependencies and the same error appears the I substitute "." for the path where I'm working. The command keeps giving me an error message even when I don't use "path_to_working_directory".

Any hints?

**Comment by bwemheu** [comment]
Thanks for th comment. A bug which should be fixed now.
