### ISSUE TITLE
cannot find function buildDependencies()

### ISSUE THREAD

**Issue by Hugh-Zhu** [bwemheu/Tax4Fun2#5]
The README.md says use buildDependencies(...) to install dependencies. But I cannot find this function or the package that contains it even after googling the issue.

Although those dependencies can be installed manually, I still think the function buildDependencies() should be clarified. Which R version and which package to use buildDependencies()?

**Comment by bwemheu** [comment]
Hi,

I introduced the function in later packages. I will modify the readme to make that clear. Thanks fur your suggestion.

Best
