### ISSUE TITLE
normalize_pathways don't have any effect in makeFunctionalPrediction

### ISSUE THREAD

**Issue by fjossandon** [bwemheu/Tax4Fun2#6]
Hello @bwemheu,
I was reviewing latest version **1.1.5** code, and found that the argument **normalize_pathways** don't have any effect. The reason is the following:
```
  # Converting the KO profile to a profile of KEGG pathways
  message('Converting functions to pathways')
  ko2ptw = read.delim(file.path(path_to_reference_data, 'KEGG/ko2ptw.txt'))
  if(normalize_pathways) functional_prediction_norm = functional_prediction / ko_list$pathway_count
  pathway_prediction = aggregate(x = functional_prediction[ko2ptw$nrow,], by = list(ko2ptw$ptw), sum)
```
When normalize_pathways is set to True, it goes to an IF where a new variable **functional_prediction_norm** is created with the normalization consisting in the division of the **functional_prediction** values by the number of pathways associated for each metabolic function, as specified in the ko_list file. This code piece have 2 problems:
1) **ko_list$pathway_count** don't work because in the lastest version of the KEGG files (Tax4Fun2_ReferenceData_v2.zip), the "ko_list.txt" and "ko_descripion.txt" files were merged into 1 called "ko.txt" and the corresponding column name was changed to **ptw_count**, so it would need to be **ko_list$ptw_count**.
2) If the column name above is fixed, the **functional_prediction_norm** still don't have any effect because is not used anywhere besides that IF block, so in the following line, the code continues the work with the unnormalized values. To fix it, the functional_prediction_norm values should have been copied over to **functional_prediction** variable before continuing with the process.

As a side note, it would be great if the repo had all the folders and scripts obtained through the releases, so all of them would tracked and their change history would be preserved, instead of only the License and Readme.

Best regards,

**Comment by bwemheu** [comment]
Hi,

thanks. I fixed that.

**Comment by fjossandon** [comment]
Hi again @bwemheu,
I saw that you updated the version in the Readme, but seems that there was a problem generating the release... In the release page (https://github.com/bwemheu/Tax4Fun2/releases), although a 1.1.6 tag was generated, the link only includes the files present in the repo (License and Readme), and not the actual R files. I guess this is probably because in the other releases you added an extra tarball with the R files attached as an Asset.

Because of the tarball was not added this time, the link in the readme is broken:
`wget https://github.com/bwemheu/Tax4Fun2/releases/download/1.1.6/Tax4Fun2_1.1.6.tar.gz`
And the link in the "1a) Click here" text still points to the previous 1.1.5 release version.

Maybe you could consider commiting the files to the repo?? That way they would be automatically included in the release ZIP.

Best,
