### ISSUE TITLE
Unused argument when running extractSSU.

### ISSUE THREAD

**Issue by TamarJ** [bwemheu/Tax4Fun2#8]
Hi,

I am using version 3.4.4 of R in Linux (Ubuntu 18.04.1 LTS) to run the Tax4Fun2 package.

When running the extractSSU command I receive a unused argument error (see below).

 extractSSU(genome_file = "OneProkaryoticGenome.fasta", file_extension = "fasta", path_to_reference_data = "/storage/R/Tax4Fun2/Tax4Fun2_ReferenceData_v2")
Error in extractSSU(genome_file = "OneProkaryoticGenome.fasta", file_extension = "fasta",  :
  unused argument (path_to_reference_data = "/storage/R/Tax4Fun2/Tax4Fun2_ReferenceData_v2")

I also receive this error with using path_to_reference_data = "."

/storage/R/Tax4Fun2/Tax4Fun2_ReferenceData_v2 is the correct path to the reference data.

Any assistance would be much appreciated.

Regards,
Tamar

**Comment by bwemheu** [comment]
Hi. should be fixed. A tyop in the function.

**Comment by asfoep** [comment]
Hi bwemheu, 

I am having the same problem and cannot find any way around the problem. Here is my code

genome_file="C:/....../taxa4fun2"
file_extension = "fasta" 
path_to_reference_data = "C:/........./Tax4Fun2_ReferenceData_v1.1"

# Extracting SSU sequences from a single genome
extractSSU(genome_file = "OneProkaryoticGenome.fasta", 
           file_extension = "fasta", 
           path_to_reference_data = "C:/........./Tax4Fun2_ReferenceData_v1.1")

Error in extractSSU(genome_file = "OneProkaryoticGenome.fasta", file_extension = "fasta",  : 
  unused argument (path_to_reference_data = "C:/............/Tax4Fun2_ReferenceData_v1.1")

##same if I run:
extractSSU(genome_file = "OneProkaryoticGenome.fasta", 
           file_extension = "fasta", 
           path_to_reference_data = ".")

Error in extractSSU(genome_file = "OneProkaryoticGenome.fasta", file_extension = "fasta",  : 
  unused argument (path_to_reference_data = ".")

What am I doing wrong, any help appreciated
Regards,
A
