### ISSUE TITLE
Error in calculateFunctionalRedundancy and makeFunctionalPrediction

### ISSUE THREAD

**Issue by RainUCLA** [bwemheu/Tax4Fun2#9]
Hi,

When I tried to use v1.1.5 to run calculateFunctionalRedundancy, there always said "Error in matrix(if (is.null(value)) logical() else value, nrow = nr, dimnames = list(rn,  : 
  length of 'dimnames' [2] not equal to array extent", even when I used the test data Water_otu_table.txt. I didn't have this issue before when I used v1 (very original version?), but that has been more than a year. 

In makeFunctionalPrediction, the error was "Error in aggregate.data.frame(x = otu_table_reduced[, -1], by = list(otu_table_reduced[,  : 
  no rows to aggregate"

Can you help to figure these out?

Thanks,
Rain

**Comment by bwemheu** [comment]
You Ids in the OTU table ("OtuXXXXX") and the fasta file (">OTUXXXXX") do not match.
Best,
Bernd
